# Generated by Django 4.1.3 on 2022-11-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subcategories_img', models.ImageField(upload_to='img/subcategories')),
                ('category', models.ManyToManyField(related_name='subcategory', to='catalog.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product_img', models.ImageField(upload_to='img/product')),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='In BYN/kg', max_digits=5)),
                ('on_stock', models.DecimalField(decimal_places=2, help_text='entered the stock, "kg.gr"', max_digits=5)),
                ('in_stock', models.BooleanField(help_text='in stock/ out of stock')),
                ('description', models.TextField()),
                ('nutritional_value', models.TextField()),
                ('min_pack', models.DecimalField(decimal_places=2, help_text='minimum packaging "kg.gr"', max_digits=5)),
                ('addition_date', models.DateTimeField(auto_now_add=True)),
                ('best_before', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categories')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subcategories')),
            ],
        ),
    ]
